spring.application.name=ms-register

##despues hay que borrar lo de abajo cuando se conecte a una bd real

spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration